### ISSUE TITLE
Monitor usage of the app

### ISSUE THREAD

**Issue by midgerate** [midgerate/dh-bookkeeping-web3#23]
- Check whether it is okay to use analytics on a dapp as most dapps mention that they dont use trackers. (2h)
- Check out Plausible (https://plausible.io/)
- Implement tracking (15h) - Contingent on being able to track.
- Come up with the list of things to track in the analytics. for ex. No. of times filters were used

**Comment by midgerate** [comment]
@scottrepreneur I have seen many dapps just using google analytics to track. We can do the same. But it is worth asking if Daohaus is okay with this. 

Otherwise we will drop this issue altogether.

**Comment by skuhlmann** [comment]
We are trying out plausible on the daohaus app and website now. So i think it will be fine to use that on this app too.

I can put you in touch with the Amos, who is managing that on ourside.

**Comment by midgerate** [comment]
As of now, only adding plausible and not specific feature related events. If we need it in future we will see.
